# Generated by Django 4.1 on 2022-09-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_tag_alter_article_options_scope_article_tag"),
    ]

    operations = [
        migrations.RemoveField(model_name="article", name="tag",),
        migrations.AddField(
            model_name="tag",
            name="article",
            field=models.ManyToManyField(
                related_name="tag", through="articles.Scope", to="articles.article"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="is_main",
            field=models.BooleanField(verbose_name="основной раздел"),
        ),
    ]
