# Generated by Django 4.0.6 on 2022-08-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('lug', models.SlugField()),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.DateField()),
            ],
        ),
    ]
