# Generated by Django 4.0.6 on 2022-08-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_lte_exists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='lug',
            new_name='slug',
        ),
    ]
